name: Reclaim Gnark library tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true
          cache-dependency-path: |
            go.sum
      - name: run tests
        run: go test ./...
